### ISSUE TITLE
If the CI build script fails the repo is in a mess

### ISSUE THREAD

**Issue by robertpostill** [exercism/racket#113]
In messing up the pull request for https://github.com/exercism/racket/pull/112 I learnt a bit.  Firstly what the CI process is for the racket track.  Then almost as important what one of the failure modes is.  Namely if the CI build breaks during the raco test phase the whole thing falls apart.  

More importantly it falls apart in a way that means it is really difficult to understand what drove the CI failure as git reports many files that _could_ be the culprit.  Which makes diagnosing the issue time consuming.  So what should happen is that if the build fails it changes the repo back to it's default state as much as possible but leaves the changes in place.

**Comment by timotheosh** [comment]
The CI build failed at merge time? When you submit a PR, your branch goes through the CI cycle, and it showed it passed. I don't think I follow what happened here.

**Comment by zenspider** [comment]
bump. OP?
