### ISSUE TITLE
Version File in .meta Directories

### ISSUE THREAD

**Issue by guygastineau** [exercism/racket#131]
~The new maintainer [dashboard tool](https://tracks.exercism.io/racket/master) expects to find version info for each exercise in its `exercises/slug/.meta/version`.~
EDIT: Actually the [dashboard tool](https://tracks.exercism.io/racket/master) can be set to read the version from any place.

If this track decides to continue on the path of using the `.meta/version` file to store this information, then should probably be added to the exercises here.

Additionally, I have made a script called `bin/version-sync` which has been merged.  If contributors wish to continue the currently-not-universal convention of placing the version in the test file, then the helper script will automatically create or update the version file when run after changes.

**Comment by guygastineau** [comment]
This is a list of all exercises regarding the presence of version info in the tests file with the following format:
``` racket
;; Tests adapted from `problem-specifications/canonical-data,json [version number]
```

- [ ] accumulate
- [ ] acronym
- [x] affine-cipher
- [ ] allergies
- [ ] all-your-base
- [ ] anagram
- [ ] armstrong-numbers
- [ ] bob
- [ ] collatz-conjecture
- [ ] difference-of-squares
- [ ] etl
- [ ] gigasecond
- [ ] grains
- [ ] grep
- [ ] hamming
- [ ] hello-world
- [x] isogram
- [ ] leap
- [ ] list-ops
- [ ] meetup
- [ ] nucleotide-count
- [ ] perfect-numbers
- [ ] phone-number
- [ ] raindrops
- [x] reverse-string
- [ ] rna-transcription
- [ ] roman-numerals
- [ ] say
- [ ] scrabble-score
- [ ] two-fer
- [ ] word-count

**Comment by cousinitt** [comment]
Neat - thanks for doing this.
