### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/racket#204]
This repository's `main` branch currently does not pass all CI checks.
This makes detecting issues in PRs harder and might result in a broken track, and so is an important thing to fix.

The following CI workflows are currently failing:

https://github.com/exercism/racket/runs/3371782947
https://github.com/exercism/racket/runs/3371782863

## Tracking

https://github.com/exercism/v3-launch/issues/55

**Comment by kerolloz** [comment]
@ErikSchierboom 
Tests pass here 
![image](https://user-images.githubusercontent.com/36763164/196004988-ff301abb-dd5f-4ceb-915b-627a507fe9f4.png)
