### ISSUE TITLE
Comments in stub files

### ISSUE THREAD

**Issue by arguello** [exercism/racket#23]
Should we add comments to the stub files, like @bennn did with [the grep exercise](https://github.com/exercism/xracket/blob/master/exercises/grep/grep.rkt)?

I can see the benefit for those new to Racket; at the same time, it doesn't appear to be a common practice with the other exercism langs.

**Comment by zenspider** [comment]
Link is 404

**Comment by yurrriq** [comment]
Link fixed.

**Comment by zenspider** [comment]
Honestly... I _don't_ like the idea of the extra challenge. Either drive challenges through tests or don't.

As far as the contracty comment stuff goes ? Maybe? I don't feel I need that in racket half as much as I'd like to have it in rust (which they don't do, for the record).

There shouldn't be a `main` module for any of this stuff.
