### ISSUE TITLE
Add alphametics exercise to racket track

### ISSUE THREAD

**Issue by chip** [exercism/racket#247]
Hi - I've forked this repo and was attempting to translate the alphametics exercise over to Racket using configlet:

```
./bin/configlet generate . --only alphametics
Error: invalid argument for command 'generate': '.'

----------------------

configlet 4.0.0-beta.9
The official tool for managing Exercism language track repositories.
...
```

As referenced in #99 (closed and labeled "paused"), there are broken links in the docs, so I'd appreciate any direction on converting existing exercises over to Racket. Thanks in advance for any suggestions.

**Comment by ErikSchierboom** [comment]
@chip `configlet generate` doesn't really do what you want. However, there are parts of `configlet` that you should use for a new exercises. Provided you've created an `exercises/practice/alphametics` directory, you can then run `configlet sync --update --yes --exercise alphametics`. That should sync all the appropriate files and metadata, giving you a nice starting point. Let me know if that helps.

**Comment by ErikSchierboom** [comment]
Ah yes, you'll also need to an an entry to the `config.json`. It goes in `exercises/practice`. Note that the UUID must be uniquely generated, which you can do via `configlet uuid`.
