### ISSUE TITLE
binary-search: Let's use a vector instead of a list for the sorted numbers.

### ISSUE THREAD

**Issue by dreig** [exercism/racket#323]
List access is O(N) (you have to walk from the head of the list all the way to your desired index) so binary search on a list doesn't make much sense from a performance/efficiency standpoint. Let's use vectors instead (which have constant time random access).
The Common Lisp and Scheme tracks use vectors too.

**Comment by BNAndras** [comment]
We'll break existing solutions, but I see your point. The Emacs Lisp track also uses arrays in a similar way.

PR welcome.
