### ISSUE TITLE
Very little activity in exercism/racket?

### ISSUE THREAD

**Issue by jgilray** [exercism/racket#85]
I ported a problem a couple days ago, also I noticed that ```README.md``` appears to be a little out of date with current practices in other tracks.  Finally, I noticed a PR from August 8 that seems to be lingering (it looked to me like config.json in the PR was in a bad format).  I'd be willing to help out with racket stuff.  @zenspider @kytrinyx @arguello @yurrriq I want to be sure that you see this issue - thanks.

**Comment by kytrinyx** [comment]
Thank you so much, @jgilray —would you mind opening an issue about this in https://github.com/exercism/discussions/issues?

The Racket track definitely needs some love and enthusiasm, and I wonder if we could get some of our current track maintainers from other tracks to be a "buddy" or mentor in the process.

**Comment by yurrriq** [comment]
I can likely respond within a week, but am generally very busy. If you've got time and would like to contribute more, @jgilray, that would be great. I'll post some quick thoughts on #83 shortly

**Comment by jgilray** [comment]
Hi @kytrinyx and @yurrriq, I'd be happy to help out.  I'm a relative noob here, but I have experience with racket and rust.  Since I am not a maintainer, I'm a little limited in how I can help, right?  I'm willing to do some reviews, etc.  I will work on an update to the README.md and do a PR on that tonight.  @yurrriq, should I still open an issue in ```exercism/discussions``` as @kytrinyx suggested above?

**Comment by yurrriq** [comment]
@jgilray, great! Re: the discussions issue, I defer to @kytrinyx, as (clearly) I'm not so involved in Exercism these days.

**Comment by jgilray** [comment]
Thanks for @yurrriq and @kytrinyx for helping resolve each of the problems that I originally pointed out in this issue.  Closing...
